uktrade/great-domestic-ui

- .coveragerc
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
[this task](https://uktrade.atlassian.net/browse/TT-1077)
> Add events redirects

- marketaccess/templates/marketaccess/report_a_barrier.html
- marketaccess/templates/marketaccess/report_barrier_form/success.html
- requirements.in
- requirements.txt
- requirements_test.txt
Forgot to update the requirements to the correct version so that the header link will show on great. 
Also added some content changes that popped up today.
> MarketAccess content changes / updating directory components

- contact/forms.py
[this task](https://uktrade.atlassian.net/browse/TT-1058)
these validators are useful when the target of the email is an external user.
the target of these messages is internal users.
> Remove unnecesary anti-phishing validators

- article/tests/test_views.py
- article/views.py
- conf/urls.py
[this task](https://uktrade.atlassian.net/browse/TT-1102)
> Add community article page

- community/forms.py
- community/tests/conftest.py
- community/tests/test_forms.py
- community/tests/test_views.py
- makefile
- added `agreed_terms` field
- `company_website` field made optional
> Added term and condition field to community form

- community/forms.py
- community/tests/conftest.py
- community/tests/test_forms.py
- community/tests/test_views.py
Selected choices field values added to serialized API data with label values.
> Serialized choices field label values to community form API data

- requirements.in
- requirements.txt
- requirements_test.txt
> Update components to fix header search url

- conf/urls.py
- contact/templates/contact/guidance-exporting-to-the-uk.html
- contact/tests/test_views.py
- contact/views.py
- core/views.py
> Link guidance page to exporting to UK routing

- CHANGELOG.md
- community/forms.py
- contact/forms.py
- euexit/forms.py
- finance/forms.py
- ukef/forms.py
Made consistent with other forms on site
> Tt 1452 missing captcha label contact forms

- contact/forms.py
- contact/templates/contact/domestic/step.html
- contact/templates/contact/routing/step-export-opportunities-service.html
- contact/templates/contact/routing/step-great-account.html
- contact/templates/contact/routing/step-great-services.html
Text of legends in contact forms is changed as defined [here](https://uktrade.atlassian.net/browse/GTRANSFORM-205)
> Tt 1449 accessibility add fieldsets to forms

- CHANGELOG.md
- ukef/templates/ukef/what_we_offer.html
https://uktrade.atlassian.net/browse/XOT-934
> Removed unused CSS files

- CHANGELOG.md
- conf/urls.py
https://uktrade.atlassian.net/browse/XOT-939
> Fixed camel case URLs redirections for UKEF pages 

- CHANGELOG.md
- article/templates/article/marketing_article_detail.html
- article/templates/article/marketing_article_detail_content.html
- article/views.py
- core/views.py
https://uktrade.atlassian.net/browse/XOT-922
> Marketing article page template

- CHANGELOG.md
- community/tests/test_views.py
- conf/urls.py
> Fixed no GA bug on /community/success/

- CHANGELOG.md
> Fix changelog merge issue

- CHANGELOG.md
> Changelog for 2019.08.01 release

- CHANGELOG.md
- marketing/forms.py
> XOT-977 small text change

- CHANGELOG.md
- article/tests/test_templates.py
- conf/urls.py
- core/templates/core/service_no_longer_available.html
- core/tests/test_views.py
- core/views.py
> Allow adding of new advice sections

- CHANGELOG.md
- article/templates/article/marketing_article_detail_content.html
> XOT-977 use cms page.title for correct breadcrumb

- CHANGELOG.md
- community/templates/community/join-form.html
> Xot 991 fix export advocates form breadcrumbs

- CHANGELOG.md
- casestudy/templates/casestudy/casestudy_cards.html
> Content tweak

- CHANGELOG.md
- contact/templates/contact/soo/base.html
> Xot 989 soo contact breadbrumb change

- CHANGELOG.md
- casestudy/templates/casestudy/hello-baby.html
- casestudy/templates/casestudy/york-bag.html
> GTRANSFORM-345 adding external link to case study company website

- CHANGELOG.md
- conf/urls.py
- core/tests/test_views.py
- core/views.py
> Add investment support directory redirect

- CHANGELOG.md
- search/templates/search_feedback.html
> Xot 1007 search feedback content

- CHANGELOG.md
- contact/forms.py
- contact/tests/test_forms.py
Both off:
Both on:
Just capital invest off:
Just exporting to the uk off:
> Fixed feature flag mixin and added tests

- CHANGELOG.md
- contact/forms.py
> Tidied up picking choices from feature flag

- conf/tests/test_url_redirects.py
- conf/url_redirects.py
> Red arrows redirect

- CHANGELOG.md
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
> Amend red arrows redirect url

- CHANGELOG.md
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
> Fix redirect

- CHANGELOG.md
- article/templates/article/article_detail_content.html
- article/templates/article/country_guide.html
- article/templates/article/marketing_article_detail.html
- article/templates/article/marketing_article_detail_content.html
- article/templates/article/markets_landing_page.html
- article/templates/article/sections/news_section.html
- article/tests/test_templates.py
- contact/templates/contact/guidance-exporting-to-the-uk.html
- contact/templates/contact/guidance.html
- core/templates/core/campaign.html
- core/templates/core/landing_page_domestic.html
- core/templates/core/performance_dashboard.html
- requirements.in
- requirements.txt
- requirements_test.txt
- ukef/templates/ukef/landing_page.html
- ukef/templates/ukef/what_we_offer.html
> Gtransform 338 add external link tag and directory components update

- contact/forms.py
> Content type, wrong capitalisation

- CHANGELOG.md
- euexit/views.py
> Fix incorrect url in form

- CHANGELOG.md
- marketaccess/templates/marketaccess/report_barrier_form/step-summary.html
Fix missing answer to the business type question on the summary page. If other was selected also fix bug that did not show this or the text entered.
Ensure all the questions are in the same order and with the same text.
> Fix missing answer to business type

- CHANGELOG.md
- article/templates/article/article_detail_content.html
> Xot 920 create css template

- CHANGELOG.md
- marketaccess/templates/marketaccess/report_barrier_form/step-summary.html
- [O] Change has a jira ticket that has the correct status.
> fix typo market access review submission form step

- CHANGELOG.md
- community/templates/community/join-form.html
> Fix /community/join/ breadcrumbs

- CHANGELOG.md
- contact/templates/contact/comment-contact.html
- contact/templates/contact/domestic/step.html
- contact/templates/contact/exporting/step-business.html
- contact/templates/contact/exporting/step-comment.html
- contact/templates/contact/guidance.html
- contact/templates/contact/office-finder.html
- contact/templates/contact/routing/step-domestic.html
- contact/templates/contact/routing/step-export-opportunities-service.html
- contact/templates/contact/routing/step-great-account.html
- contact/templates/contact/routing/step-great-services.html
- contact/templates/contact/routing/step-location.html
- contact/tests/test_templates.py
- euexit/templates/euexit/domestic-contact-form.html
- finance/templates/finance/lead_generation_form/step-company.html
- finance/templates/finance/lead_generation_form/step-help.html
- finance/templates/finance/lead_generation_form/step-personal.html
> Gtransform 238 non descriptive page titles

- CHANGELOG.md
- contact/forms.py
- contact/templates/contact/exporting/step-comment.html
- finance/forms.py
> Gtransform 213 unlabelled form elements

- CHANGELOG.md
- core/templates/core/includes/cms_content.html
> Gtransform 368 add accessibility cms page

- CHANGELOG.md
- core/templates/core/info_page.html
> GTRANSFORM-368 change base file for missing css

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> GTRANSFORM-368 change list bullet colour

- CHANGELOG.md
- article/templates/article/article_list.html
- article/templates/article/topic_list_base.html
- conf/url_redirects.py
- conf/urls.py
- core/templates/core/landing_page_alternate.html
- core/templates/core/services.html
- marketaccess/templates/marketaccess/report_a_barrier.html
- requirements.in
- requirements.txt
- requirements_test.txt
- ukef/templates/ukef/contact_form.html
- ukef/templates/ukef/country_cover.html
- ukef/templates/ukef/home_page.html
- ukef/templates/ukef/includes/card.html
- ukef/templates/ukef/landing_page.html
- ukef/tests/test_views.py
- ukef/views.py
> Fix IE hero bug

- CHANGELOG.md
- README.md
- requirements.in
- requirements.txt
- requirements_test.txt
> Upgrade directory components to fix js in non-chrome

- CHANGELOG.md
- conf/settings.py
- healthcheck/backends.py
> disabled backend in non-test-environments

- CHANGELOG.md
- article/templates/article/article_detail_content.html
- core/templates/core/landing_page_alternate.html
- requirements.in
- requirements.txt
- requirements_test.txt
> Xot 1114 add video transcript component and components update

- CHANGELOG.md
- article/templates/article/country_guide.html
> Fix missing hero image on country guides

- CHANGELOG.md
- finance/templates/finance/trade_finance.html
- finance/views.py
> UKEF bug fixes

- CHANGELOG.md
- search/templates/search-key-pages.json
> Fix trade barrier link

- CHANGELOG.md
- contact/views.py
- sso/models.py
- sso/tests/test_models.py
> Add user full name from new registration journey to SOO contact form

- finance/templates/finance/includes/get_finance_cta.html
> XOT-1078 fix incorrect class

- CHANGELOG.md
- content/templates/content/country_guide.html
> XOT-1118 use cms title as page title

- CHANGELOG.md
- conf/settings.py
> Silence captcha key checks

- CHANGELOG.md
- contact/views.py
- sso/models.py
- sso/tests/test_models.py
> add profile phone number to contact form

- CHANGELOG.md
- search/templates/search-key-pages.json
> fix search key pages  link

- CHANGELOG.md
- marketaccess/templates/marketaccess/report_barrier_form/success.html
> Fix success message on market access success page

- CHANGELOG.md
- core/templates/core/landing_page_alternate.html
> XOT-1137 swap padding to fix potential spacing issue wihtout chevron

- conf/urls.py
No changelog ticket for this one.
> fix conf/urls.py

- CHANGELOG.md
- contact/forms.py
> XOT-1117 - small spelling change

- CHANGELOG.md
- contact/forms.py
- contact/tests/test_views.py
- core/validators.py
- marketing/forms.py
- pytest.ini
> Handle invalid postcodes on office finder

- CHANGELOG.md
- search/templates/search-key-pages.json
> Xot 1195 replicate chevron fix

- CHANGELOG.md
- core/static/js/dit.components.video.js
- core/templates/core/landing_page.html
> Xot 1200 video autoplay

- CHANGELOG.md
- conf/url_redirects.py
> XOT-1171 Add redirects

- CHANGELOG.md
- content/tests/test_templates.py
- content/tests/test_views.py
- content/views.py
Reverts uktrade/great-domestic-ui#419
Revert as putting this change in UI only
> Revert "XOT-1185 change sort param for country guides"

- CHANGELOG.md
- content/tests/test_views.py
- content/views.py
> XOT-1118 filter out The prefix on UI sort function

- .gitignore
- CHANGELOG.md
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
> adding a new redirect to JPM fintech week

- CHANGELOG.md
> Update changelog production release 2019.11.25

- CHANGELOG.md
- conf/settings.py
- makefile
- requirements.in
- requirements.txt
- requirements_test.txt
- search/helpers.py
> Upgrade sentry client

- CHANGELOG.md
- contact/templates/contact/office-finder.html
> TT2185 update postcode not found error

- content/templates/content/markets_landing_page.html
> XOT-1224 text changes

- content/templates/content/markets_landing_page.html
> Xot 1224 market landing

- CHANGELOG.md
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
> redirecting /about/ page to DIT about page. events footer links to it

- CHANGELOG.md
- content/templates/content/markets_landing_page.html
> No ticket change market filters onload event

- requirements.in
- requirements.txt
- requirements_test.txt
> Hotifix cookie modal

- CHANGELOG.md
- community/tests/test_views.py
- contact/tests/test_views.py
- euexit/tests/test_views.py
- finance/tests/test_views.py
- marketaccess/tests/test_views.py
- marketing/tests/test_views.py
- requirements.in
- requirements.txt
- requirements_test.txt
- search/forms.py
- ukef/tests/test_views.py
> Search form will only send data to database, not Zendesk

- marketaccess/templates/marketaccess/report_barrier_form/step-summary.html
> Show report trade barrier country name

- CHANGELOG.md
- core/templates/core/performance_dashboard.html
> XOT-1341 - change templates

- CHANGELOG.md
- conf/url_redirects.py
- contact/tests/test_views.py
> (TT-2334) Added redirect for old form to new form

- CHANGELOG.md
- core/static/js/dit.js
> GAA-21_fix_expander_keyboard_control

- CHANGELOG.md
- contact/templates/contact/soo/base.html
> Fixed header tag

- CHANGELOG.md
- contact/templates/contact/soo/base.html
> Staging release

- CHANGELOG.md
- core/forms.py
> GBAU-77-fix-mandatory-fields 

- CHANGELOG.md
> Release CL update

- CHANGELOG.md
- euexit/templates/euexit/form-contents.html
> Added autocomplete attribute for contact form

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
- search/tests/test_views.py
- search/views.py
> Upgraded directory-form-api-client

- CHANGELOG.md
- community/templates/community/join-form.html
- contact/templates/contact/export-voucher-form.html
- contact/templates/contact/office-finder.html
- contact/templates/contact/wizard-domestic.html
- contact/templates/contact/wizard-international.html
- finance/templates/finance/lead_generation_form/base.html
- marketaccess/templates/marketaccess/report_barrier_form/base.html
> Added autocomplete attribute to forms

- CHANGELOG.md
> Release 1.1.0 CL update

- CHANGELOG.md
> Post release 2.0.0 CL update

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> Directory-component upgraded

- CHANGELOG.md
- requirements.in
- requirements.txt
- requirements_test.txt
> Updating requirements: Django to latest patched version of 2.2

- CHANGELOG.md
- conf/tests/test_url_redirects.py
- conf/url_redirects.py
sibling ticket to be created in great-cms so that we dont lose it over post GP2 launch.
> add redirect in great-domestic from /companion/

- CHANGELOG.md
- content/tests/test_templates.py
- requirements.in
- requirements.txt
- requirements_test.txt
> GP2-2784: Bump directory-components

- CHANGELOG.md
- package.json
- yarn.lock
> NOTICKET: Upgrade yargs-parser in line with dependabot alert
